#!/bin/bash

# Setup script for configuring external repositories
# This script helps you configure the traceability system to work with external repos

set -e

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║     External Repository Setup for Traceability Matrix System         ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

# Get current directory
TRACEABILITY_ROOT=$(pwd)

# Function to prompt for directory
prompt_directory() {
    local prompt_message=$1
    local default_value=$2
    local var_name=$3
    
    echo "$prompt_message"
    echo "Default: $default_value"
    read -p "Enter path (or press Enter for default): " user_input
    
    if [ -z "$user_input" ]; then
        eval "$var_name='$default_value'"
    else
        # Expand ~ to home directory
        user_input="${user_input/#\~/$HOME}"
        eval "$var_name='$user_input'"
    fi
}

echo "📋 Step 1: Locate External Repositories"
echo "========================================"
echo ""

# Prompt for pulse-services location
prompt_directory \
    "Where is your pulse-services repository?" \
    "$HOME/repos/pulse-services" \
    "SERVICES_PATH"

# Prompt for qa-test-scenarios location
prompt_directory \
    "Where is your qa-test-scenarios repository?" \
    "$HOME/repos/qa-test-scenarios" \
    "SCENARIOS_PATH"

echo ""
echo "📋 Step 2: Verify Paths"
echo "======================="
echo ""

# Verify services path
if [ ! -d "$SERVICES_PATH" ]; then
    echo "❌ ERROR: Services path does not exist: $SERVICES_PATH"
    exit 1
fi
echo "✅ Services path exists: $SERVICES_PATH"

# Verify scenarios path
if [ ! -d "$SCENARIOS_PATH" ]; then
    echo "❌ ERROR: Scenarios path does not exist: $SCENARIOS_PATH"
    exit 1
fi
echo "✅ Scenarios path exists: $SCENARIOS_PATH"

# Check for baseline directory
if [ ! -d "$SCENARIOS_PATH/baseline" ]; then
    echo "⚠️  WARNING: baseline/ directory not found in scenarios repo"
    echo "   Creating baseline directory..."
    mkdir -p "$SCENARIOS_PATH/baseline"
    echo "✅ Created: $SCENARIOS_PATH/baseline"
fi

# Check for ai_cases directory
if [ ! -d "$SCENARIOS_PATH/ai_cases" ]; then
    echo "ℹ️  Creating ai_cases directory..."
    mkdir -p "$SCENARIOS_PATH/ai_cases"
    echo "✅ Created: $SCENARIOS_PATH/ai_cases"
fi

echo ""
echo "📋 Step 3: Create Environment Configuration"
echo "==========================================="
echo ""

# Create .env file
cat > "$TRACEABILITY_ROOT/.env" << EOF
# External Repository Configuration
# Generated by setup-external-repos.sh on $(date)

# Service Repository Path
SERVICE_PATH=$SERVICES_PATH

# QA Test Scenarios Path (points to baseline directory)
TEST_SCENARIO_PATH=$SCENARIOS_PATH/baseline

# AI Configuration
CLAUDE_API_KEY=${CLAUDE_API_KEY:-your-api-key-here}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-your-api-key-here}

# Optional: Verbose logging
# VERBOSE=true
EOF

echo "✅ Created .env file with external paths"
echo ""

# Check if API key is set
if [ -z "$CLAUDE_API_KEY" ] && [ -z "$ANTHROPIC_API_KEY" ]; then
    echo "⚠️  WARNING: No AI API key found"
    echo "   Please update .env file with your Claude API key"
    echo ""
fi

echo "📋 Step 4: Update Config (Optional - for permanent setup)"
echo "=========================================================="
echo ""

# Ask if user wants to update config.json
read -p "Do you want to update .traceability/config.json for permanent setup? (y/n): " update_config

if [ "$update_config" = "y" ] || [ "$update_config" = "Y" ]; then
    # Backup existing config
    if [ -f "$TRACEABILITY_ROOT/.traceability/config.json" ]; then
        cp "$TRACEABILITY_ROOT/.traceability/config.json" "$TRACEABILITY_ROOT/.traceability/config.json.backup"
        echo "✅ Backed up existing config to config.json.backup"
    fi
    
    # Update config with external paths
    cat > "$TRACEABILITY_ROOT/.traceability/config.json" << EOF
{
  "externalPaths": {
    "servicesRoot": "$SERVICES_PATH",
    "testCasesRoot": "$SCENARIOS_PATH"
  },
  "projectRoot": ".",
  "services": [
    {
      "name": "customer-service",
      "enabled": true,
      "path": "customer-service",
      "language": "java",
      "testFramework": "junit",
      "testDirectory": "src/test/java",
      "testPattern": "*Test.java"
    },
    {
      "name": "identity-service",
      "enabled": true,
      "path": "identity-service",
      "language": "java",
      "testFramework": "junit",
      "testDirectory": "src/test/java",
      "testPattern": "*Test.java"
    }
  ],
  "ai": {
    "provider": "anthropic",
    "model": "auto",
    "temperature": 0.3,
    "maxTokens": 2000,
    "batchSize": 3,
    "fallbackProviders": ["anthropic"]
  },
  "testCases": {
    "baselineDirectory": ".traceability/test-cases/baseline",
    "aiCasesDirectory": ".traceability/test-cases/ai_cases",
    "reportsDirectory": ".traceability/test-cases/reports"
  }
}
EOF
    echo "✅ Updated config.json with external paths"
fi

echo ""
echo "📋 Step 5: Copy Existing Data (if needed)"
echo "=========================================="
echo ""

# Check if services exist in local directory
if [ -d "$TRACEABILITY_ROOT/services" ]; then
    read -p "Copy services from ./services/ to $SERVICES_PATH? (y/n): " copy_services
    if [ "$copy_services" = "y" ] || [ "$copy_services" = "Y" ]; then
        cp -r "$TRACEABILITY_ROOT/services/"* "$SERVICES_PATH/"
        echo "✅ Copied services to external repository"
    fi
fi

# Check if baseline exists locally
if [ -d "$TRACEABILITY_ROOT/.traceability/test-cases/baseline" ]; then
    read -p "Copy baseline scenarios to $SCENARIOS_PATH/baseline? (y/n): " copy_baseline
    if [ "$copy_baseline" = "y" ] || [ "$copy_baseline" = "Y" ]; then
        cp -r "$TRACEABILITY_ROOT/.traceability/test-cases/baseline/"* "$SCENARIOS_PATH/baseline/"
        echo "✅ Copied baseline scenarios to external repository"
    fi
fi

# Check if ai_cases exists locally
if [ -d "$TRACEABILITY_ROOT/.traceability/test-cases/ai_cases" ]; then
    read -p "Copy AI cases to $SCENARIOS_PATH/ai_cases? (y/n): " copy_ai_cases
    if [ "$copy_ai_cases" = "y" ] || [ "$copy_ai_cases" = "Y" ]; then
        cp -r "$TRACEABILITY_ROOT/.traceability/test-cases/ai_cases/"* "$SCENARIOS_PATH/ai_cases/"
        echo "✅ Copied AI cases to external repository"
    fi
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                          Setup Complete! ✅                           ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Next Steps:"
echo ""
echo "1. Verify the setup:"
echo "   source .env"
echo "   node bin/ai-continue identity-service"
echo ""
echo "2. You should see path configuration:"
echo "   📁 Path Configuration:"
echo "      Services: $SERVICES_PATH (ENV: SERVICE_PATH)"
echo "      Scenarios: $SCENARIOS_PATH/baseline (ENV: TEST_SCENARIO_PATH)"
echo ""
echo "3. Commit changes to external repos:"
echo "   cd $SERVICES_PATH"
echo "   git add ."
echo "   git commit -m \"Add service code from traceability setup\""
echo "   git push"
echo ""
echo "   cd $SCENARIOS_PATH"
echo "   git add ."
echo "   git commit -m \"Add QA scenarios from traceability setup\""
echo "   git push"
echo ""
echo "4. Optional: Update .gitignore to exclude old directories"
echo ""
echo "For more information, see: docs/EXTERNAL_REPOS.md"
echo ""
