#!/bin/bash

# Consolidated External Repository Setup Script
# Combines quick setup and full clone/migrate workflows

set -e

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║     External Repository Setup for Traceability Matrix System         ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

# Configuration
TRACEABILITY_ROOT=$(pwd)
GITHUB_SERVICES_REPO="https://github.com/aquibshakeel/pulse-services"
GITHUB_SCENARIOS_REPO="https://github.com/aquibshakeel/qa-test-scenario"

# Function to prompt for directory
prompt_directory() {
    local prompt_message=$1
    local default_value=$2
    local var_name=$3
    
    echo "$prompt_message"
    echo "Default: $default_value"
    read -p "Enter path (or press Enter for default): " user_input
    
    if [ -z "$user_input" ]; then
        eval "$var_name='$default_value'"
    else
        # Expand ~ to home directory
        user_input="${user_input/#\~/$HOME}"
        eval "$var_name='$user_input'"
    fi
}

# Show menu
echo "Choose setup workflow:"
echo ""
echo "1. Quick Setup (I already have the repositories cloned)"
echo "2. Full Setup (Clone from GitHub, copy data, commit & push)"
echo "3. Exit"
echo ""
read -p "Enter choice (1-3): " choice
echo ""

case $choice in
    1)
        # Quick Setup Workflow
        echo "╔══════════════════════════════════════════════════════════════╗"
        echo "║              Quick Setup - Existing Repositories              ║"
        echo "╚══════════════════════════════════════════════════════════════╝"
        echo ""
        
        echo "📋 Step 1: Locate External Repositories"
        echo "========================================"
        echo ""
        
        # Prompt for pulse-services location
        prompt_directory \
            "Where is your pulse-services repository?" \
            "$HOME/Desktop/pulse-services" \
            "SERVICES_PATH"
        
        # Prompt for qa-test-scenarios location
        prompt_directory \
            "Where is your qa-test-scenarios repository?" \
            "$HOME/Desktop/qa-test-scenario" \
            "SCENARIOS_PATH"
        
        echo ""
        echo "📋 Step 2: Verify Paths"
        echo "======================="
        echo ""
        
        # Verify services path
        if [ ! -d "$SERVICES_PATH" ]; then
            echo "❌ ERROR: Services path does not exist: $SERVICES_PATH"
            exit 1
        fi
        echo "✅ Services path exists: $SERVICES_PATH"
        
        # Verify scenarios path
        if [ ! -d "$SCENARIOS_PATH" ]; then
            echo "❌ ERROR: Scenarios path does not exist: $SCENARIOS_PATH"
            exit 1
        fi
        echo "✅ Scenarios path exists: $SCENARIOS_PATH"
        
        # Check for baseline directory
        if [ ! -d "$SCENARIOS_PATH/baseline" ]; then
            echo "⚠️  WARNING: baseline/ directory not found in scenarios repo"
            echo "   Creating baseline directory..."
            mkdir -p "$SCENARIOS_PATH/baseline"
            echo "✅ Created: $SCENARIOS_PATH/baseline"
        fi
        
        # Check for ai_cases directory
        if [ ! -d "$SCENARIOS_PATH/ai_cases" ]; then
            echo "ℹ️  Creating ai_cases directory..."
            mkdir -p "$SCENARIOS_PATH/ai_cases"
            echo "✅ Created: $SCENARIOS_PATH/ai_cases"
        fi
        
        echo ""
        echo "📋 Step 3: Create Environment Configuration"
        echo "==========================================="
        echo ""
        
        # Create .env file
        cat > "$TRACEABILITY_ROOT/.env" << EOF
# External Repository Configuration
# Generated by setup-repos.sh on $(date)

# Service Repository Path
SERVICE_PATH=$SERVICES_PATH

# QA Test Scenarios Path (points to baseline directory)
TEST_SCENARIO_PATH=$SCENARIOS_PATH/baseline

# AI Configuration
CLAUDE_API_KEY=${CLAUDE_API_KEY:-your-api-key-here}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-your-api-key-here}

# Optional: Verbose logging
# VERBOSE=true
EOF
        
        echo "✅ Created .env file with external paths"
        echo ""
        
        # Check if API key is set
        if [ -z "$CLAUDE_API_KEY" ] && [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "⚠️  WARNING: No AI API key found"
            echo "   Please update .env file with your Claude API key"
            echo ""
        fi
        
        echo "📋 Step 4: Copy Existing Data (Optional)"
        echo "=========================================="
        echo ""
        
        # Check if services exist in local directory
        if [ -d "$TRACEABILITY_ROOT/services" ]; then
            read -p "Copy services from ./services/ to $SERVICES_PATH? (y/n): " copy_services
            if [ "$copy_services" = "y" ] || [ "$copy_services" = "Y" ]; then
                cp -r "$TRACEABILITY_ROOT/services/"* "$SERVICES_PATH/"
                echo "✅ Copied services to external repository"
            fi
        fi
        
        # Check if baseline exists locally
        if [ -d "$TRACEABILITY_ROOT/.traceability/test-cases/baseline" ]; then
            read -p "Copy baseline scenarios to $SCENARIOS_PATH/baseline? (y/n): " copy_baseline
            if [ "$copy_baseline" = "y" ] || [ "$copy_baseline" = "Y" ]; then
                cp -r "$TRACEABILITY_ROOT/.traceability/test-cases/baseline/"* "$SCENARIOS_PATH/baseline/"
                echo "✅ Copied baseline scenarios to external repository"
            fi
        fi
        
        # Check if ai_cases exists locally
        if [ -d "$TRACEABILITY_ROOT/.traceability/test-cases/ai_cases" ]; then
            read -p "Copy AI cases to $SCENARIOS_PATH/ai_cases? (y/n): " copy_ai_cases
            if [ "$copy_ai_cases" = "y" ] || [ "$copy_ai_cases" = "Y" ]; then
                cp -r "$TRACEABILITY_ROOT/.traceability/test-cases/ai_cases/"* "$SCENARIOS_PATH/ai_cases/"
                echo "✅ Copied AI cases to external repository"
            fi
        fi
        
        echo ""
        echo "╔══════════════════════════════════════════════════════════════╗"
        echo "║                    Setup Complete! ✅                         ║"
        echo "╚══════════════════════════════════════════════════════════════╝"
        echo ""
        echo "🚀 Next Steps:"
        echo ""
        echo "1. Load environment variables:"
        echo "   source .env"
        echo ""
        echo "2. Run traceability analysis:"
        echo "   node bin/ai-continue identity-service"
        echo ""
        echo "3. You should see:"
        echo "   📁 Path Configuration:"
        echo "      Services: $SERVICES_PATH (ENV: SERVICE_PATH)"
        echo "      Scenarios: $SCENARIOS_PATH/baseline (ENV: TEST_SCENARIO_PATH)"
        echo ""
        echo "📖 Documentation:"
        echo "   - Quick Start: docs/GETTING_STARTED.md"
        echo "   - External Repos: docs/EXTERNAL_REPOS.md"
        echo ""
        ;;
        
    2)
        # Full Setup Workflow
        echo "╔══════════════════════════════════════════════════════════════╗"
        echo "║        Full Setup - Clone, Copy, Commit & Push               ║"
        echo "╚══════════════════════════════════════════════════════════════╝"
        echo ""
        
        # Prompt for clone location
        prompt_directory \
            "Where should repositories be cloned?" \
            "$HOME/Desktop" \
            "CLONE_LOCATION"
        
        # Verify clone location exists
        if [ ! -d "$CLONE_LOCATION" ]; then
            echo "❌ ERROR: Clone location does not exist: $CLONE_LOCATION"
            exit 1
        fi
        
        echo ""
        echo "📋 Step 1: Clone External Repositories"
        echo "======================================="
        echo ""
        
        # Clone pulse-services
        if [ -d "$CLONE_LOCATION/pulse-services" ]; then
            echo "⚠️  pulse-services already exists at $CLONE_LOCATION/pulse-services"
            read -p "Remove and re-clone? (y/n): " remove_services
            if [ "$remove_services" = "y" ]; then
                rm -rf "$CLONE_LOCATION/pulse-services"
                echo "Cloning pulse-services..."
                cd "$CLONE_LOCATION"
                git clone "$GITHUB_SERVICES_REPO"
            fi
        else
            echo "Cloning pulse-services..."
            cd "$CLONE_LOCATION"
            git clone "$GITHUB_SERVICES_REPO"
        fi
        
        # Clone qa-test-scenario
        if [ -d "$CLONE_LOCATION/qa-test-scenario" ]; then
            echo "⚠️  qa-test-scenario already exists at $CLONE_LOCATION/qa-test-scenario"
            read -p "Remove and re-clone? (y/n): " remove_scenarios
            if [ "$remove_scenarios" = "y" ]; then
                rm -rf "$CLONE_LOCATION/qa-test-scenario"
                echo "Cloning qa-test-scenario..."
                cd "$CLONE_LOCATION"
                git clone "$GITHUB_SCENARIOS_REPO"
            fi
        else
            echo "Cloning qa-test-scenario..."
            cd "$CLONE_LOCATION"
            git clone "$GITHUB_SCENARIOS_REPO"
        fi
        
        echo "✅ Repositories cloned"
        echo ""
        
        # Set paths
        SERVICES_PATH="$CLONE_LOCATION/pulse-services"
        SCENARIOS_PATH="$CLONE_LOCATION/qa-test-scenario"
        
        echo "📋 Step 2: Copy Services to pulse-services Repository"
        echo "====================================================="
        echo ""
        
        if [ -d "$TRACEABILITY_ROOT/services" ]; then
            echo "Copying services..."
            
            # Copy identity-service
            if [ -d "$TRACEABILITY_ROOT/services/identity-service" ]; then
                cp -r "$TRACEABILITY_ROOT/services/identity-service" "$SERVICES_PATH/"
                echo "✅ Copied identity-service"
            fi
            
            # Copy customer-service
            if [ -d "$TRACEABILITY_ROOT/services/customer-service" ]; then
                cp -r "$TRACEABILITY_ROOT/services/customer-service" "$SERVICES_PATH/"
                echo "✅ Copied customer-service"
            fi
            
            # Commit and push
            cd "$SERVICES_PATH"
            git add .
            if git diff --cached --quiet; then
                echo "ℹ️  No changes to commit in pulse-services"
            else
                git commit -m "Initial commit: Add services from traceability-matrix-system

- Added identity-service with unit tests
- Added customer-service with unit tests"
                git push origin main
                echo "✅ Pushed services to GitHub"
            fi
        else
            echo "⚠️  No services directory found in traceability repo"
        fi
        
        echo ""
        echo "📋 Step 3: Copy Scenarios to qa-test-scenario Repository"
        echo "========================================================="
        echo ""
        
        # Create directory structure
        mkdir -p "$SCENARIOS_PATH/baseline"
        mkdir -p "$SCENARIOS_PATH/ai_cases"
        echo "✅ Created baseline/ and ai_cases/ directories"
        
        if [ -d "$TRACEABILITY_ROOT/.traceability/test-cases/baseline" ]; then
            echo "Copying baseline scenarios..."
            cp -r "$TRACEABILITY_ROOT/.traceability/test-cases/baseline/"* "$SCENARIOS_PATH/baseline/" 2>/dev/null || true
            echo "✅ Copied baseline scenarios"
        fi
        
        if [ -d "$TRACEABILITY_ROOT/.traceability/test-cases/ai_cases" ]; then
            echo "Copying AI cases..."
            cp -r "$TRACEABILITY_ROOT/.traceability/test-cases/ai_cases/"* "$SCENARIOS_PATH/ai_cases/" 2>/dev/null || true
            echo "✅ Copied AI cases"
        fi
        
        # Commit and push
        cd "$SCENARIOS_PATH"
        git add .
        if git diff --cached --quiet; then
            echo "ℹ️  No changes to commit in qa-test-scenario"
        else
            git commit -m "Initial commit: Add QA test scenarios from traceability-matrix-system

- Added baseline scenarios for identity-service
- Added baseline scenarios for customer-service
- Added AI-generated scenarios for review"
            git push origin main
            echo "✅ Pushed scenarios to GitHub"
        fi
        
        echo ""
        echo "📋 Step 4: Configure Traceability System"
        echo "========================================="
        echo ""
        
        cd "$TRACEABILITY_ROOT"
        
        # Create .env file
        cat > .env << EOF
# External Repository Configuration
# Generated by setup-repos.sh on $(date)

# Service Repository Path (cloned on Desktop)
SERVICE_PATH=$SERVICES_PATH

# QA Test Scenarios Path (cloned on Desktop)
TEST_SCENARIO_PATH=$SCENARIOS_PATH/baseline

# AI Configuration
CLAUDE_API_KEY=${CLAUDE_API_KEY:-your-api-key-here}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-your-api-key-here}

# Optional: Verbose logging
# VERBOSE=true
EOF
        
        echo "✅ Created .env file with paths:"
        echo "   SERVICE_PATH=$SERVICES_PATH"
        echo "   TEST_SCENARIO_PATH=$SCENARIOS_PATH/baseline"
        echo ""
        
        # Check API key
        if [ -z "$CLAUDE_API_KEY" ] && [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "⚠️  WARNING: No API key found in environment"
            echo "   Please update .env file with your Claude API key"
            echo ""
        fi
        
        echo "📋 Step 5: Test the Setup"
        echo "========================="
        echo ""
        
        echo "Testing path resolution..."
        echo ""
        
        # Source the .env
        source .env
        
        echo "Environment variables loaded:"
        echo "  SERVICE_PATH: $SERVICE_PATH"
        echo "  TEST_SCENARIO_PATH: $TEST_SCENARIO_PATH"
        echo ""
        
        # Verify paths exist
        if [ -d "$SERVICE_PATH/identity-service" ]; then
            echo "✅ identity-service found at $SERVICE_PATH/identity-service"
        else
            echo "❌ identity-service NOT found"
        fi
        
        if [ -f "$TEST_SCENARIO_PATH/identity-service-baseline.yml" ]; then
            echo "✅ identity-service-baseline.yml found"
        else
            echo "❌ identity-service-baseline.yml NOT found"
        fi
        
        echo ""
        echo "╔══════════════════════════════════════════════════════════════╗"
        echo "║                    Setup Complete! 🎉                         ║"
        echo "╚══════════════════════════════════════════════════════════════╝"
        echo ""
        echo "📁 Repository Locations:"
        echo "   Services:  $SERVICES_PATH"
        echo "   Scenarios: $SCENARIOS_PATH"
        echo "   GitHub:    https://github.com/aquibshakeel/pulse-services"
        echo "   GitHub:    https://github.com/aquibshakeel/qa-test-scenario"
        echo ""
        echo "🚀 Next Steps:"
        echo ""
        echo "1. Load environment variables:"
        echo "   source .env"
        echo ""
        echo "2. Run traceability analysis:"
        echo "   node bin/ai-continue identity-service"
        echo ""
        echo "3. You should see:"
        echo "   📁 Path Configuration:"
        echo "      Services: $SERVICES_PATH (ENV: SERVICE_PATH)"
        echo "      Scenarios: $SCENARIOS_PATH/baseline (ENV: TEST_SCENARIO_PATH)"
        echo ""
        echo "4. View your repos on GitHub:"
        echo "   - https://github.com/aquibshakeel/pulse-services"
        echo "   - https://github.com/aquibshakeel/qa-test-scenario"
        echo ""
        echo "📖 Documentation:"
        echo "   - Quick Start: docs/GETTING_STARTED.md"
        echo "   - External Repos: docs/EXTERNAL_REPOS.md"
        echo ""
        ;;
        
    3)
        echo "Setup cancelled."
        exit 0
        ;;
        
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac
